### PR TITLE
Update Feeder

### PR DESCRIPTION
**Pull request by lshiwjx**
Accelerate data reading

### CODE REVIEW

**Comment by yjxiong** [comment]
Can you explain why using mmap() can accelerate date reading?

**Comment by lshiwjx** [comment]
It saves the time of loading data (~90G for kinetics) to memory.

**Comment by yjxiong** [comment]
Thanks. Do you have a benchmark on the loading time for future reference?

**Comment by yjxiong** [comment]
And also have tested the training & testing?

**Comment by lshiwjx** [comment]
I found that using mmap will save the time when loading array from disk to memroy for NTU-RGB+D, but will slow the reading time since it need to read the data from disk. But for Kinetics, both the loading and reading time are saved when applying mmap. I don't know why it is the case.

`Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    28                                           def loader():
    29         1      33405.0  33405.0      0.1      data1 = np.load('/home/lshi/Database/NTU-RGB-D/xview/train_data.npy', mmap_mode='r')
    30         1    3317391.0 3317391.0     11.2      data2 = np.load('/home/lshi/Database/NTU-RGB-D/xview/train_data.npy')
    31         1         75.0     75.0      0.0      d1 = data1[0]
    32         1          2.0      2.0      0.0      d2 = data2[0]
    33         1       1396.0   1396.0      0.0      data1 = np.load('/home/lshi/Database/kinetics-skeleton/train_data.npy', mmap_mode='r')
    34         1   26253490.0 26253490.0     88.6      data2 = np.load('/home/lshi/Database/kinetics-skeleton/train_data.npy')
    35         1         84.0     84.0      0.0      d1 = data1[0]
    36         1      19371.0  19371.0      0.1      d2 = data2[0]`

**Comment by yjxiong** [comment]
Thanks. In this case please make the mmap read as an option that a user can turn at his own choice.

More information on how the mmap works. It works by mapping a file on a disk to a virtual address in the memory space. When the application reads a part of the file it loads that part (one page or pages) into physical memory. If the file is smaller than the physical memory space available it will eventually be fully loaded into the memory cache and provides fast access. And by reading and caching in parallel, it saves the upfront time cost for reading the whole file into memory.

Regarding your benchmark, it is possible that Numpy needs some initialization of the array in the first read so only benchmarking reading `data[0]` might not be accurate. A more appropriate way to assess this is to run a lot of random accesses and measure the average reading speed.

**Comment by lshiwjx** [comment]
Thanks for your suggestion.
I tried randomly reading 30000 items (nearly an epoch) with function 

```
def loader():
    read_sequence = list(np.random.randint(0, 37645, 30000))
    data1 = np.load('/home/lshi/Database/NTU-RGB-D/xview/train_data.npy', mmap_mode='r')
    data2 = np.load('/home/lshi/Database/NTU-RGB-D/xview/train_data.npy')
    d1 = [data1[i] for i in read_sequence]
    d2 = [data2[i] for i in read_sequence]
    data1 = np.load('/home/lshi/Database/kinetics-skeleton/train_data.npy', mmap_mode='r')
    data2 = np.load('/home/lshi/Database/kinetics-skeleton/train_data.npy')
    d1 = [data1[i] for i in read_sequence]
    d2 = [data2[i] for i in read_sequence]
```

The profilier results for each line:

```
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
    1                                           
    2         1       2774.0   2774.0      0.0  
    3         1       2166.0   2166.0      0.0  
    4         1    2942547.0 2942547.0     14.3  
    5         1     157747.0 157747.0      0.8  
    6         1      11982.0  11982.0      0.1  
    7         1       1402.0   1402.0      0.0  
    8         1   17331282.0 17331282.0     84.1  
    9         1     126236.0 126236.0      0.6  
    10         1      26869.0  26869.0      0.1 
```
I will change it to an option.

**Comment by yjxiong** [comment]
Thanks for your contribution.

The benchmark now reflects the mechanism of mmap. If you the mmap saves the upfront reading time but since it's reading from disk afterward it will be slower per read. However, if you have enough RAM available and run a huge number of reads (its the case for training ST-GCN) the whole file will be cached into RAM. Then the two approaches will have similar average reading speed.

**Pull request merged**
