### PR TITLE
use command line arguments

### PR DESCRIPTION
**Pull request by Chevrefeuille**
Sorry for the late modifications...
I quickly adapted the code to use command line arguments, what do you think of it?

### CODE REVIEW

**Comment by yjxiong** [comment]
Nice! 

Thank you @Chevrefeuille !

**Comment by GimSungwoo** [comment]
Super useful work!
Just one question, when I use this script to generate the data set. I found that the frames are not saved in the increasing order. like random sort.
Will it influence the result when feeding the data set to the model?
In other words, is it necessary to save the frames in the increasing order, which is the same as your original dataset.

Many Thanks
Kim

**Comment by yjxiong** [comment]
@GimSungwoo 
The input sequence needs to be in the temporal order for ST-GCN to work

**Comment by GimSungwoo** [comment]
@yjxiong yep, thank you for replying. 
how about this situation - if every frame has correct frame_index, but they are just not sorted in increasing order in terms of frame index.

**Comment by Chevrefeuille** [comment]
I think that it does not matter because here
[https://github.com/yysijie/st-gcn/blob/d3995ce1a1021bdedb76a79783f7bde0063900ff/st_gcn/feeder/feeder_kinetics.py#L111-L122](url)
the data is reordered using the frame indexes. 
@yjxion and @yysijie , correct me if am wrong.

**Comment by yjxiong** [comment]
Yes, the framework will sort the frames. Just keep in mind that the input to the network needs to be temporally ordered.

**Comment by GimSungwoo** [comment]
Cool, Cheers for informing

**Comment by bryancresswell** [comment]
Just a curious question, in tools/kinetics_gendata.py, I see that you are able to find top 5 predictions and then choose the top 2. Can that be implemented in this script?

**Comment by Chevrefeuille** [comment]
I actually wrote a script to extract the two skeletons with the highest confidence score but that are consistent throughout the clips (because if someone passes by closer to the camera, in my case his skeleton would be used instead of the ones of the two people I am really interested in).  Basically I just take the skeletons with the minimal average distance to the original ones at each frame. I can share it if you are interested.

**Comment by bryancresswell** [comment]
Hey man,

That would be great, could you share it?

**Comment by Chevrefeuille** [comment]
No problem:
```python
import os
from pathlib import Path
import json
import itertools
import argparse


def find_most_confident(skeletons):
    """
    Return the two skeletons with the largest average confidences and closest gravity center
    """
    data = []
    for skeleton in skeletons:
        n_joints = len(skeleton['score'])
        coordinates = skeleton['pose']
        average_confidence = sum(skeleton['score']) / n_joints
        x, y = [], []
        for i in range(0, len(coordinates), 2):
            x += [coordinates[i]]
            y += [coordinates[i+1]]
        center_of_gravity = (sum(x) / n_joints, sum(y) / n_joints)
        data += [(skeleton, average_confidence, center_of_gravity)]
    sorted_by_confidence = sorted(data, key=lambda c: c[1], reverse=True)

    best_s1, best_s2 = [], []
    best_distance = 1
    for pair in itertools.combinations(sorted_by_confidence, 2):
        s1, _, g1 = pair[0]
        s2, _, g2 = pair[1]
        distance = ((g1[0] - g2[0])**2 + (g1[1] - g2[1])**2)**.5
        if distance < best_distance:
            best_s1, best_s2 = s1, s2

    return best_s1, best_s2

def find_consistent(skeletons, s1):
    """
    Return the skeleton which is consistent with the skeletons s1
    """
    average_distances = []
    for skeleton in skeletons:
        coordinates = skeleton['pose']
        average_distance = 0
        n_joints = len(skeleton['score'])
        for i in range(0, len(coordinates), 2):
            x1, y1 = s1['pose'][i], s1['pose'][i+1]
            x, y = coordinates[i], coordinates[i+1]
            d = ((x1 - x)**2 + (y1 - y)**2)**.5
            average_distance += d
        average_distance /= n_joints
        # print(average_distance)
        average_distances += [(skeleton, average_distance)]

    sorted_by_distance = sorted(average_distances, key=lambda c: c[1])
    return sorted_by_distance[0][0]


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description='Confident and consistent skeletons extractor.')
    # folder that will contain the converted files (one per video)
    parser.add_argument('--json_path', default='data/poses/st-gcn_format')

    arg = parser.parse_args()

    p = Path(arg.json_path)
    
    for path in p.glob('*.json'):
        json_path = str(path)
        if 'consistent' not in json_path:
            dest_path = '{}_consistent.json'.format(json_path.rstrip('.json'))
            data = json.load(open(json_path))
            frames = data['data']
            ordered_frames = sorted(frames, key=lambda k: k['frame_index'])
            first_frame = ordered_frames[0]
            first_skeletons = first_frame['skeleton']
            s1, s2 = find_most_confident(first_skeletons)
            consistent_1, consistent_2 = {}, {}
            consistent_frames = []
            for frame in ordered_frames:
                skeletons = frame['skeleton']
                consistent_1 = find_consistent(skeletons, s1)
                skeletons.remove(consistent_1)
                if len(skeletons) >= 1:
                    consistent_2 = find_consistent(skeletons, s2)
                s1, s2 = consistent_1, consistent_2
                consistent_frames += [{
                    'skeleton': [consistent_1, consistent_2],
                    'frame_index': frame['frame_index']
                    }]
            data['data'] = consistent_frames
            with open(dest_path, 'w') as outfile:
                print('Creating {}'.format(dest_path))
                json.dump(data, outfile)
```

Actually, now I start by taking the two skeletons that are closest to one another and with the biggest confidence score. You can forget the computation of the distances in the `find_most_confident` function and directly take the two first element of the `sorted_by_confidence` array.

**Comment by yjxiong** [comment]
Cool script! 

Actually, the current "two skeletons" requirement is somewhat artificial. You can run as many skeleton sequences in a video as you want, using the TSN style training which was used in the current two skeleton scheme. You can try this if you want to work with actions requiring more than two people involved.

**Comment by liurui16** [comment]
@Chevrefeuille .Thanks for providing such a good script.
I try to run this script but it feedback me nothing.So I want to ask
How to use the script"extract the two skeletons with the highest confidence score"based on yysijie's work?what I have to prepare for using this script?

**Comment by huanglai666** [comment]
> Cool script!
> 
> Actually, the current "two skeletons" requirement is somewhat artificial. You can run as many skeleton sequences in a video as you want, using the TSN style training which was used in the current two skeleton scheme. You can try this if you want to work with actions requiring more than two people involved.

@yjxiong would you test different size of skeleton sequences , for example 3 people, and do you have any conclution ,thank you

**Comment by yjxiong** [comment]
@huanglai666 

No we don't have this result and will not have it in near future. You are welcome to try it by yourself.

**Pull request merged**
